# Non-live sample Home Assistant configuration.

homeassistant:
  packages: !include_dir_named packages

automation ui: !include automations.yaml
automation agent: !include_dir_merge_list automations

lovelace:
  mode: yaml
  dashboards:
    wall-panel:
      mode: yaml
      title: Wall Panel
      icon: mdi:tablet-dashboard
      show_in_sidebar: true
      filename: dashboards/wall-panel.yaml

